const sections = [
    {slug: "bosses", name: "Bosses", category: "boss"},
    {slug: "characters", name: "Characters", category: "character"},
    {slug: "enemies", name: "Enemies", category: "enemy"},
    {slug: "items", name: "Items", category: "item"},
    {slug: "objects", name: "Objects", category: "object"}
]

const sprites = [
    {category: "boss", slug: "aquamentus", name: "Aquamentus", path: "TLoZ_Aquamentus_Sprite.png"},
    {category: "boss", slug: "digdogger-big", name: "Digdogger, Big", path: "TLoZ_Digdogger_Sprite.png"},
    {category: "boss", slug: "digdogger-small", name: "Digdogger, Small", path: "TLoZ_Digdogger_Sprite_2.png"},
    {category: "boss", slug: "dodongo-bombed-front", name: "Dodongo, Bombed Front", path: "TLoZ_Dodongo_Bombed_Sprite_2.png"},
    {category: "boss", slug: "dodongo-bombed-side", name: "Dodongo, Bombed Side", path: "TLoZ_Dodongo_Bombed_Sprite.png"},
    {category: "boss", slug: "dodongo-front", name: "Dodongo, Front", path: "TLoZ_Dodongo_Sprite_2.png"},
    {category: "boss", slug: "dodongo-side", name: "Dodongo, Side", path: "TLoZ_Dodongo_Sprite.png"},
    {category: "boss", slug: "ganon-damage", name: "Ganon, Damage", path: "TLoZ_Ganon_Sprite_2.png"},
    {category: "boss", slug: "ganon-leap", name: "Ganon, Leap", path: "TLoZ_Ganon_Sprite_4.png"},
    {category: "boss", slug: "ganon-squat", name: "Ganon, Squat", path: "TLoZ_Ganon_Sprite.png"},
    {category: "boss", slug: "ganon-stand", name: "Ganon, Stand", path: "TLoZ_Ganon_Sprite_3.png"},
    {category: "boss", slug: "ganon-wave", name: "Ganon, Wave", path: "TLoZ_Ganon_Sprite_5.png"},
    {category: "boss", slug: "ganon-weakened-damage", name: "Ganon, Weakened Damage", path: "TLoZ_Ganon_Weakened_Sprite_2.png"},
    {category: "boss", slug: "ganon-weakened-squat", name: "Ganon, Weakened Squat", path: "TLoZ_Ganon_Weakened_Sprite.png"},
    {category: "boss", slug: "gleeok-1-headed", name: "Gleeok, 1-Headed", path: "TLoZ_Gleeok_One-Headed_Sprite.png"},
    {category: "boss", slug: "gleeok-2-headed", name: "Gleeok, 2-Headed", path: "TLoZ_Gleeok_Two-Headed_Sprite.png"},
    {category: "boss", slug: "gleeok-3-headed", name: "Gleeok, 3-Headed", path: "TLoZ_Gleeok_Three-Headed_Sprite.png"},
    {category: "boss", slug: "gleeok-4-headed", name: "Gleeok, 4-Headed", path: "TLoZ_Gleeok_Four-Headed_Sprite.png"},
    {category: "boss", slug: "gohma-blue", name: "Gohma, Blue", path: "TLoZ_Gohma_Blue_Sprite.png"},
    {category: "boss", slug: "gohma-red", name: "Gohma, Red", path: "TLoZ_Gohma_Red_Sprite.png"},
    {category: "boss", slug: "lanmola-blue", name: "Lanmola, Blue", path: "TLoZ_Lanmola_Blue_Sprite.png"},
    {category: "boss", slug: "lanmola-red", name: "Lanmola, Red", path: "TLoZ_Lanmola_Red_Sprite.png"},
    {category: "boss", slug: "manhandla", name: "Manhandla", path: "TLoZ_Manhandla_Sprite.png"},
    {category: "boss", slug: "moldorm", name: "Moldorm", path: "TLoZ_Moldorm_Sprite.png"},
    {category: "boss", slug: "patra", name: "Patra", path: "TLoZ_Patra_Sprite.png"},
    {category: "character", slug: "goriya-hungry", name: "Goriya, Hungry", path: "TLoZ_Hungry_Goriya_Sprite.png"},
    {category: "character", slug: "link-blue-ring-holy-shield", name: "Link, Blue Ring Holy Shield", path: "TLoZ_Link_Blue_Ring_Sprite_2.png"},
    {category: "character", slug: "link-blue-ring-wooden-shield", name: "Link, Blue Ring Wooden Shield", path: "TLoZ_Link_Blue_Ring_Sprite.png"},
    {category: "character", slug: "link-holy-shield", name: "Link, Holy Shield", path: "TLoZ_Link_Sprite_2.png"},
    {category: "character", slug: "link-pale", name: "Link, Pale", path: "TLoZ_Link_Sprite_4.png"},
    {category: "character", slug: "link-red-ring-holy-shield", name: "Link, Red Ring Holy Shield", path: "TLoZ_Link_Red_Ring_Sprite_2.png"},
    {category: "character", slug: "link-red-ring-wooden-shield", name: "Link, Red Ring Wooden Shield", path: "TLoZ_Link_Red_Ring_Sprite.png"},
    {category: "character", slug: "link-side", name: "Link, Side", path: "TLoZ_Link_Sprite_3.png"},
    {category: "character", slug: "link-static", name: "Link, Static", path: "TLoZ_Link_Sprite_6.png"},
    {category: "character", slug: "link-sword", name: "Link, Sword", path: "TLoZ_Link_Sprite_5.png"},
    {category: "character", slug: "link-wooden-shield", name: "Link, Wooden Shield", path: "TLoZ_Link_Sprite.png"},
    {category: "character", slug: "merchant-green", name: "Merchant, Green", path: "TLoZ_Merchant_Sprite.png"},
    {category: "character", slug: "merchant-red", name: "Merchant, Red", path: "TLoZ_Merchant_Sprite_3.png"},
    {category: "character", slug: "merchant-white", name: "Merchant, White", path: "TLoZ_Merchant_Sprite_2.png"},
    {category: "character", slug: "moblin-generous", name: "Moblin, Generous", path: "TLoZ_Generous_Moblin_Sprite.png"},
    {category: "character", slug: "old-man", name: "Old Man", path: "TLoZ_Old_Man_Sprite.png"},
    {category: "character", slug: "old-woman", name: "Old Woman", path: "TLoZ_Old_Woman_Sprite.png"},
    {category: "character", slug: "zelda-green", name: "Zelda, Green", path: "TLoZ_Zelda_Sprite.png"},
    {category: "character", slug: "zelda-red", name: "Zelda, Red", path: "TLoZ_Zelda_Sprite_3.png"},
    {category: "character", slug: "zelda-white", name: "Zelda, White", path: "TLoZ_Zelda_Sprite_2.png"},
    {category: "enemy", slug: "armos", name: "Armos", path: "TLoZ_Armos_Sprite.png"},
    {category: "enemy", slug: "bubble-blue", name: "Bubble, Blue", path: "TLoZ_Bubble_Blue_Sprite.png"},
    {category: "enemy", slug: "bubble-flashing", name: "Bubble, Flashing", path: "TLoZ_Bubble_Sprite_2.png"},
    {category: "enemy", slug: "bubble-red", name: "Bubble, Red", path: "TLoZ_Bubble_Red_Sprite.png"},
    {category: "enemy", slug: "darknut-blue-front", name: "Darknut, Blue Front", path: "TLoZ_Darknut_Blue_Sprite.png"},
    {category: "enemy", slug: "darknut-blue-side", name: "Darknut, Blue Side", path: "TLoZ_Darknut_Blue_Sprite_2.png"},
    {category: "enemy", slug: "darknut-red-front", name: "Darknut, Red Front", path: "TLoZ_Darknut_Red_Sprite.png"},
    {category: "enemy", slug: "darknut-red-side", name: "Darknut, Red Side", path: "TLoZ_Darknut_Red_Sprite_2.png"},
    {category: "enemy", slug: "gel-black", name: "Gel, Black", path: "TLoZ_Gel_Sprite_4.png"},
    {category: "enemy", slug: "gel-blue", name: "Gel, Blue", path: "TLoZ_Gel_Sprite_2.png"},
    {category: "enemy", slug: "gel-gray", name: "Gel, Gray", path: "TLoZ_Gel_Sprite_6.png"},
    {category: "enemy", slug: "gel-green", name: "Gel, Green", path: "TLoZ_Gel_Sprite_3.png"},
    {category: "enemy", slug: "ghini", name: "Ghini", path: "TLoZ_Ghini_Sprite.png"},
    {category: "enemy", slug: "gibdo", name: "Gibdo", path: "TLoZ_Gibdo_Sprite.png"},
    {category: "enemy", slug: "goriya-blue-front", name: "Goriya, Blue Front", path: "TLoZ_Goriya_Blue_Sprite.png"},
    {category: "enemy", slug: "goriya-blue-side", name: "Goriya, Blue Side", path: "TLoZ_Goriya_Blue_Sprite_2.png"},
    {category: "enemy", slug: "goriya-red-front", name: "Goriya, Red Front", path: "TLoZ_Goriya_Red_Sprite.png"},
    {category: "enemy", slug: "goriya-red-side", name: "Goriya, Red Side", path: "TLoZ_Goriya_Red_Sprite_2.png"},
    {category: "enemy", slug: "keese-black", name: "Keese, Black", path: "TLoZ_Keese_Sprite_2.png"},
    {category: "enemy", slug: "keese-blue", name: "Keese, Blue", path: "TLoZ_Keese_Sprite.png"},
    {category: "enemy", slug: "keese-vire", name: "Keese, Vire", path: "TLoZ_Keese_Vire_Sprite.png"},
    {category: "enemy", slug: "leever-blue", name: "Leever, Blue", path: "TLoZ_Leever_Blue_Sprite.png"},
    {category: "enemy", slug: "leever-red", name: "Leever, Red", path: "TLoZ_Leever_Red_Sprite.png"},
    {category: "enemy", slug: "like-like", name: "Like Like", path: "TLoZ_Like_Like_Sprite.png"},
    {category: "enemy", slug: "lynel-blue-front", name: "Lynel, Blue Front", path: "TLoZ_Lynel_Blue_Sprite.png"},
    {category: "enemy", slug: "lynel-blue-side", name: "Lynel, Blue Side", path: "TLoZ_Lynel_Blue_Sprite_2.png"},
    {category: "enemy", slug: "lynel-red-front", name: "Lynel, Red Front", path: "TLoZ_Lynel_Red_Sprite.png"},
    {category: "enemy", slug: "lynel-red-side", name: "Lynel, Red Side", path: "TLoZ_Lynel_Red_Sprite_2.png"},
    {category: "enemy", slug: "moblin-blue-front", name: "Moblin, Blue Front", path: "TLoZ_Moblin_Blue_Sprite.png"},
    {category: "enemy", slug: "moblin-blue-side", name: "Moblin, Blue Side", path: "TLoZ_Moblin_Blue_Sprite_2.png"},
    {category: "enemy", slug: "moblin-red-front", name: "Moblin, Red Front", path: "TLoZ_Moblin_Red_Sprite.png"},
    {category: "enemy", slug: "moblin-red-side", name: "Moblin, Red Side", path: "TLoZ_Moblin_Red_Sprite_2.png"},
    {category: "enemy", slug: "octorok-blue", name: "Octorok, Blue", path: "TLoZ_Octorok_Blue_Sprite.png"},
    {category: "enemy", slug: "octorok-red", name: "Octorok, Red", path: "TLoZ_Octorok_Red_Sprite.png"},
    {category: "enemy", slug: "peahat", name: "Peahat", path: "TLoZ_Peahat_Sprite.png"},
    {category: "enemy", slug: "pols-voice-beige", name: "Pols Voice, Beige", path: "TLoZ_Pols_Voice_Sprite_4.png"},
    {category: "enemy", slug: "pols-voice-green", name: "Pols Voice, Green", path: "TLoZ_Pols_Voice_Sprite.png"},
    {category: "enemy", slug: "pols-voice-red", name: "Pols Voice, Red", path: "TLoZ_Pols_Voice_Sprite_3.png"},
    {category: "enemy", slug: "rock", name: "Rock", path: "TLoZ_Rock_Sprite.png"},
    {category: "enemy", slug: "rope-flashing", name: "Rope, Flashing", path: "TLoZ_Rope_Flashing_Sprite.png"},
    {category: "enemy", slug: "rope", name: "Rope", path: "TLoZ_Rope_Sprite.png"},
    {category: "enemy", slug: "stalfos", name: "Stalfos", path: "TLoZ_Stalfos_Sprite.png"},
    {category: "enemy", slug: "tektite-blue", name: "Tektite, Blue", path: "TLoZ_Tektite_Blue_Sprite.png"},
    {category: "enemy", slug: "tektite-red", name: "Tektite, Red", path: "TLoZ_Tektite_Red_Sprite.png"},
    {category: "enemy", slug: "vire", name: "Vire", path: "TLoZ_Vire_Sprite.png"},
    {category: "enemy", slug: "wallmaster", name: "Wallmaster", path: "TLoZ_Wallmaster_Sprite.png"},
    {category: "enemy", slug: "wizzrobe-blue", name: "Wizzrobe, Blue", path: "TLoZ_Wizzrobe_Blue_Sprite.png"},
    {category: "enemy", slug: "wizzrobe-red", name: "Wizzrobe, Red", path: "TLoZ_Wizzrobe_Red_Sprite.png"},
    {category: "enemy", slug: "zol-black", name: "Zol, Black", path: "TLoZ_Zol_Sprite_2.png"},
    {category: "enemy", slug: "zol-gray", name: "Zol, Gray", path: "TLoZ_Zol_Sprite_4.png"},
    {category: "enemy", slug: "zol-green", name: "Zol, Green", path: "TLoZ_Zol_Sprite_3.png"},
    {category: "enemy", slug: "zora-front", name: "Zora, Front", path: "TLoZ_Zora_Sprite.png"},
    {category: "enemy", slug: "zora-top", name: "Zora, Top", path: "TLoZ_Zora_Sprite_2.png"},
    {category: "item", slug: "arrow-green", name: "Arrow, Green", path: "TLoZ_Arrow_Sprite.png"},
    {category: "item", slug: "arrow-red", name: "Arrow, Red", path: "TLoZ_Arrow_Sprite_3.png"},
    {category: "item", slug: "arrow-silver", name: "Arrow, Silver", path: "TLoZ_Silver_Arrow_Sprite.png"},
    {category: "item", slug: "arrow-white", name: "Arrow, White", path: "TLoZ_Arrow_Sprite_2.png"},
    {category: "item", slug: "bomb", name: "Bomb", path: "TLoZ_Bomb_Sprite.png"},
    {category: "item", slug: "book", name: "Book", path: "TLoZ_Book_of_Magic_Sprite.png"},
    {category: "item", slug: "boomerang-beige", name: "Boomerang, Beige", path: "TLoZ_Boomerang_Sprite_4.png"},
    {category: "item", slug: "boomerang-green", name: "Boomerang, Green", path: "TLoZ_Boomerang_Sprite.png"},
    {category: "item", slug: "boomerang-magical-blue", name: "Boomerang, Magical Blue", path: "TLoZ_Magical_Boomerang_Sprite.png"},
    {category: "item", slug: "boomerang-red", name: "Boomerang, Red", path: "TLoZ_Boomerang_Sprite_3.png"},
    {category: "item", slug: "boomerang-silver", name: "Boomerang, Silver", path: "TLoZ_Boomerang_Sprite_2.png"},
    {category: "item", slug: "bow-green", name: "Bow, Green", path: "TLoZ_Bow_Sprite.png"},
    {category: "item", slug: "bow-red", name: "Bow, Red", path: "TLoZ_Bow_Sprite_3.png"},
    {category: "item", slug: "candle-blue", name: "Candle, Blue", path: "TLoZ_Blue_Candle_Sprite.png"},
    {category: "item", slug: "candle-red", name: "Candle, Red", path: "TLoZ_Red_Candle_Sprite.png"},
    {category: "item", slug: "clock", name: "Clock", path: "TLoZ_Clock_Sprite.png"},
    {category: "item", slug: "compass", name: "Compass", path: "TLoZ_Compass_Sprite.png"},
    {category: "item", slug: "fairy", name: "Fairy", path: "TLoZ_Fairy_Sprite.png"},
    {category: "item", slug: "fire", name: "Fire", path: "TLoZ_Fire_Sprite.png"},
    {category: "item", slug: "food", name: "Food", path: "TLoZ_Food_Sprite.png"},
    {category: "item", slug: "heart-container", name: "Heart Container", path: "TLoZ_Container_Heart_Sprite.png"},
    {category: "item", slug: "heart", name: "Heart", path: "TLoZ_Heart_Sprite.png"},
    {category: "item", slug: "key-magical", name: "Key, Magical", path: "TLoZ_Magical_Key_Sprite.png"},
    {category: "item", slug: "key", name: "Key", path: "TLoZ_Key_Sprite.png"},
    {category: "item", slug: "ladder", name: "Ladder", path: "TLoZ_Stepladder_Sprite.png"},
    {category: "item", slug: "letter", name: "Letter", path: "TLoZ_Letter_Sprite.png"},
    {category: "item", slug: "map", name: "Map", path: "TLoZ_Map_Sprite.png"},
    {category: "item", slug: "potion-blue", name: "Potion, Blue", path: "TLoZ_Life_Potion_Sprite.png"},
    {category: "item", slug: "potion-red", name: "Potion, Red", path: "TLoZ_2nd_Potion_Sprite.png"},
    {category: "item", slug: "power-bracelet", name: "Power Bracelet", path: "TLoZ_Power_Bracelet_Sprite.png"},
    {category: "item", slug: "raft-green", name: "Raft, Green", path: "TLoZ_Raft_Sprite_4.png"},
    {category: "item", slug: "raft-red", name: "Raft, Red", path: "TLoZ_Raft_Sprite_3.png"},
    {category: "item", slug: "raft-white", name: "Raft, White", path: "TLoZ_Raft_Sprite_2.png"},
    {category: "item", slug: "recorder", name: "Recorder", path: "TLoZ_Recorder_Sprite.png"},
    {category: "item", slug: "ring-blue", name: "Ring, Blue", path: "TLoZ_Blue_Ring_Sprite.png"},
    {category: "item", slug: "ring-red", name: "Ring, Red", path: "TLoZ_Red_Ring_Sprite.png"},
    {category: "item", slug: "rod-magical", name: "Rod, Magical", path: "TLoZ_Magical_Rod_Sprite.png"},
    {category: "item", slug: "rupees-five", name: "Rupees, Five", path: "TLoZ_5_Rupees_Sprite.png"},
    {category: "item", slug: "shield-magical", name: "Shield, Magical", path: "TLoZ_Magical_Shield_Sprite_2.png"},
    {category: "item", slug: "shield-wooden", name: "Shield, Wooden", path: "TLoZ_Wooden_Shield_Sprite_2.png"},
    {category: "item", slug: "sword-magical-tilted", name: "Sword, Magical Tilted", path: "TLoZ_Magical_Sword_Sprite.png"},
    {category: "item", slug: "sword-magical", name: "Sword, Magical", path: "TLoZ_Magical_Sword_Sprite_2.png"},
    {category: "item", slug: "sword-white", name: "Sword, White", path: "TLoZ_White_Sword_Sprite.png"},
    {category: "item", slug: "sword-wooden-green", name: "Sword, Wooden Green", path: "TLoZ_Sword_Sprite.png"},
    {category: "item", slug: "sword-wooden-red", name: "Sword, Wooden Red", path: "TLoZ_Sword_Sprite_3.png"},
    {category: "item", slug: "triforce-piece", name: "Triforce Piece", path: "TLoZ_Triforce_Sprite.png"},
    {category: "object", slug: "grave", name: "Grave", path: "TLoZ_Grave_Sprite.png"},
    {category: "object", slug: "statue-1-blueblue", name: "Statue 1, blueblue", path: "TLoZ_Stone_Statue_Sprite_01.png"},
    {category: "object", slug: "statue-1-bluegray", name: "Statue 1, bluegray", path: "TLoZ_Stone_Statue_Sprite_17.png"},
    {category: "object", slug: "statue-1-bluegreen", name: "Statue 1, bluegreen", path: "TLoZ_Stone_Statue_Sprite_07.png"},
    {category: "object", slug: "statue-1-blueyellow", name: "Statue 1, blueyellow", path: "TLoZ_Stone_Statue_Sprite_23.png"},
    {category: "object", slug: "statue-1-cyanwhite", name: "Statue 1, cyanwhite", path: "TLoZ_Stone_Statue_Sprite_09.png"},
    {category: "object", slug: "statue-1-graywhite", name: "Statue 1, graywhite", path: "TLoZ_Stone_Statue_Sprite_11.png"},
    {category: "object", slug: "statue-1-greengray", name: "Statue 1, greengray", path: "TLoZ_Stone_Statue_Sprite_15.png"},
    {category: "object", slug: "statue-1-greengreen", name: "Statue 1, greengreen", path: "TLoZ_Stone_Statue_Sprite_03.png"},
    {category: "object", slug: "statue-1-redorange", name: "Statue 1, redorange", path: "TLoZ_Stone_Statue_Sprite_05.png"},
    {category: "object", slug: "statue-1-redpink", name: "Statue 1, redpink", path: "TLoZ_Stone_Statue_Sprite_21.png"},
    {category: "object", slug: "statue-1-redwhite", name: "Statue 1, redwhite", path: "TLoZ_Stone_Statue_Sprite_13.png"},
    {category: "object", slug: "statue-1-redyellow", name: "Statue 1, redyellow", path: "TLoZ_Stone_Statue_Sprite_19.png"},
    {category: "object", slug: "statue-2-blueblue", name: "Statue 2, blueblue", path: "TLoZ_Stone_Statue_Sprite_02.png"},
    {category: "object", slug: "statue-2-bluegray", name: "Statue 2, bluegray", path: "TLoZ_Stone_Statue_Sprite_18.png"},
    {category: "object", slug: "statue-2-bluegreen", name: "Statue 2, bluegreen", path: "TLoZ_Stone_Statue_Sprite_08.png"},
    {category: "object", slug: "statue-2-blueyellow", name: "Statue 2, blueyellow", path: "TLoZ_Stone_Statue_Sprite_24.png"},
    {category: "object", slug: "statue-2-cyanwhite", name: "Statue 2, cyanwhite", path: "TLoZ_Stone_Statue_Sprite_10.png"},
    {category: "object", slug: "statue-2-graywhite", name: "Statue 2, graywhite", path: "TLoZ_Stone_Statue_Sprite_12.png"},
    {category: "object", slug: "statue-2-greengray", name: "Statue 2, greengray", path: "TLoZ_Stone_Statue_Sprite_16.png"},
    {category: "object", slug: "statue-2-greengreen", name: "Statue 2, greengreen", path: "TLoZ_Stone_Statue_Sprite_04.png"},
    {category: "object", slug: "statue-2-redorange", name: "Statue 2, redorange", path: "TLoZ_Stone_Statue_Sprite_06.png"},
    {category: "object", slug: "statue-2-redpink", name: "Statue 2, redpink", path: "TLoZ_Stone_Statue_Sprite_22.png"},
    {category: "object", slug: "statue-2-redwhite", name: "Statue 2, redwhite", path: "TLoZ_Stone_Statue_Sprite_14.png"},
    {category: "object", slug: "statue-2-redyellow", name: "Statue 2, redyellow", path: "TLoZ_Stone_Statue_Sprite_20.png"},
    {category: "object", slug: "trap", name: "Trap", path: "TLoZ_Trap_Sprite.png"},
    {category: "object", slug: "tree-brown", name: "Tree, Brown", path: "TLoZ_Tree_Sprite_2.png"},
    {category: "object", slug: "tree-green", name: "Tree, Green", path: "TLoZ_Tree_Sprite.png"}
  ];
